### ISSUE TITLE
Export Task not working

### ISSUE THREAD

**Issue by bbaermann** [systopia/de.systopia.sqltasks#101]
After creating an nearly empty task, and trying to export it, Browser shows:

"Not Found 
The requested URL was not found on this server."

The URL in my case was: http://localhost/civicrm/sqltasks/export?id=1

This behaviour is with latest master branch.

**Comment by pfigel** [comment]
Does this still happen if you open `/civicrm/menu/rebuild` first?

I suspect we just need to add a cache flush in an upgrader somewhere.

**Comment by bbaermann** [comment]
still happening after rebuild. 

The correct URL should be http://localhost/test/civicrm/sqltasks/export?id=1

so i suppose it has to do with the way i build my testing environment here and it is maybe not a sqltask bug at all. I will look into it.

**Comment by pfigel** [comment]
Ah, I see what's happening here - I used an absolute URL instead of going through `crmUrl`. 😅 

#102 should resolve this. Thanks for reporting!

**Comment by bbaermann** [comment]
Great, Thanks!
