### ISSUE TITLE
Task exported from version 1.0.0 not correctly imported to version 2.0-beta1 

### ISSUE THREAD

**Issue by peth-systopia** [systopia/de.systopia.sqltasks#108]
I imported a simple task to version 2.0-beta1 for testing purposes. It was exported from version 1.0.0 before. The main SQL was imported correctly, however the included API action was not created and had to be added manually. After doing so, the task was executed successfully.

The .sqltask file I used (I had to zip it up since github doesn't allow uploading .sqltask files):
[Prefix To Gender.zip](https://github.com/systopia/de.systopia.sqltasks/files/11048340/Prefix.To.Gender.zip)

**Comment by bjendres** [comment]
@pfigel Could you have a quick look at this? If I recall correctly, somebody at @greenpeace-cee contributed the legacy importer code.

**Comment by bjendres** [comment]
> Can you test this against #109?

Will do, thanks.

**Comment by bjendres** [comment]
@peth-systopia will give it a try
