### ISSUE TITLE
Fatal error: non-static function called statically

### ISSUE THREAD

**Issue by MegaphoneJon** [systopia/de.systopia.sqltasks#113]
I saw this error in my logs:

```
php Error: Non-static method CRM_Sqltasks_Action_APICall::getDefaultOrder() cannot be called statically in CRM_Sqltasks_Action::getAllActions() (line 297 of /var/www/mysite.org/web/sites/all/civicrm-custom/extensions/de.systopia.sqltasks/CRM/Sqltasks/Action.php)
```

Should we make `getDefaultOrder()` static? Or should we instantiate the class and make all of the calls in `getAllActions()` non-static?

**Comment by bjendres** [comment]
Thanks @MegaphoneJon.

@pfigel Could you have a brief look? It's (rightfully) complaining about [THIS LINE](https://github.com/systopia/de.systopia.sqltasks/blob/2.0.0/CRM/Sqltasks/Action.php#L297), where it's statically calling a _non-static_ method. The next line, however, correctly calls the *static* function (``isDefaultTemplateAction``) in the same way.

**Comment by pfigel** [comment]
I reckon it would make sense to go with the "make it static" option for consistency. Eventually, I can see this bit of code get replaced by something more flexible anyway (that other extensions can hook into, or use some action-provider-ish thing to add custom actions).
