### ISSUE TITLE
Incorrect SQL task runs "forever"

### ISSUE THREAD

**Issue by UeNu9** [systopia/de.systopia.sqltasks#118]
I created an SQL task with a syntax error in the test system, and ran it.
Now, after correcting the task, I cannot run it again. I always get the error message 
"Logs:
    [Task 1] Task is still running. Execution skipped."
Even after waiting a day, this error still occurs.
It seems like as the SQL does not return a success message, it is considered not finished. I think this is undesired behavior.

**Comment by bjendres** [comment]
Yes, you'll have to manually reset the ``running_since`` entry in the SQL task table ( ``civicrm_sqltasks``):
```
UPDATE civicrm_sqltasks SET running_since=NULL WHERE id = [YOUR TASK ID];
```

Sorry this isn't very convenient, but it rarely happens beyond the trying out phase of tasks life cycle. That being said, PRs always welcome :)
