### ISSUE TITLE
Smarty V3 compliance

### ISSUE THREAD

**Issue by VangelisP** [systopia/de.systopia.sqltasks#120]
.. which essentially means upgrade civix and then review if all the forms appear correctly

**Comment by bjendres** [comment]
Hi @VangelisP, thanks. Would you be able to give it a shot?

**Comment by VangelisP** [comment]
> Hi @VangelisP, thanks. Would you be able to give it a shot?

Yes, working on a PR at the moment and checking the results/menus/functionality ;)

I intentionally opened this issue to be used as a placeholder/reference for the PR

**Comment by jensschuppe** [comment]
I added this to the (closed) `2.1` milestone, as `2.2` seems to be far ahead and this is a minor fix for a patch-level version on the `2.1` version branch, IMO.
