### ISSUE TITLE
Contact.delete-api-calls break after a single execution

### ISSUE THREAD

**Issue by thomst** [systopia/de.systopia.sqltasks#13]
Configure a SqlTask to make a Contact.delete-api-call.
The api-call will only be called once - irrespectively of the size of your result-table.

**Comment by thomst** [comment]
Looking into the code there is no obvious reason for this behavior.
It is just that $query->fetch() returns nothing as soon as an Contact.delete-api-call was done.
There must be a weird interference within dao-handling between a query-object and a Contact.delete-api-call.
Here is a patch with a workaround...
[sqltask-extension-api-delete.patch.txt](https://github.com/systopia/de.systopia.sqltasks/files/2031273/sqltask-extension-api-delete.patch.txt)

**Comment by systopia** [comment]
@patf You've done something there, could you have a look?

**Comment by patf** [comment]
I believe this was recently fixed as a side-effect of https://github.com/civicrm/civicrm-core/pull/12276. Prior to this PR, `CRM_Contact_BAO_Contact::deleteContact()` used to contain a call to `CRM_Core_DAO::freeResult()`, which presumably would clear the result set after the first call.

Upgrading to >= 5.4.0 or applying that patch should resolve this issue.

**Comment by systopia** [comment]
@patf so that means that we probably won't fix that, right? Or should we implement the workaround as discussed at the spring?

**Comment by patf** [comment]
@systopia We're happy with the core patch as a workaround (which we had previously applied to fix a memory leak), and with the 5.x upgrade being on the roadmap anyway, wontfix is okay for us.
