### ISSUE TITLE
Run API calls without "Data Table" defined?

### ISSUE THREAD

**Issue by mattwire** [systopia/de.systopia.sqltasks#3]
For example, I want to run the Navigation.reset API with params for=all.  I do not have any Data Table in this case.

**Comment by systopia** [comment]
Hi @mattwire.

I'm sorry, I have no idea what you're talking about. Could you elaborate?

**Comment by mattwire** [comment]
This is what I wanted to do:
![bec-cave org uk_administrator__option com_civicrm task civicrm_sqltasks_configure reset 1 tid 1](https://user-images.githubusercontent.com/2052161/32414516-cf5d3e64-c220-11e7-84a0-0502864aa39d.png)

But I don't think I should specify anything in parameter "Data Table"?  But it is a mandatory field.

**Comment by systopia** [comment]
The whole point of the SQL-Tasks is that it's SQL-driven. For that reason, I don't think we can drop the data table as a source. As a workaround, just create a one-line view or table...

**Comment by systopia** [comment]
@mattwire Would you agree? @patf What's your opinion?

**Comment by mattwire** [comment]
I think I put table name "civicrm_navigation" in there.  It seems a little strange to put a table in that is never used but it does work :-)

**Comment by systopia** [comment]
> I think I put table name "civicrm_navigation" in there. It seems a little strange to put a table in that is never used but it does work :-)

Well, that just means that your API is called once for *every* entry in that table. Is that what you wanted?

I would have done something like:
``
DROP VIEW tmp_matts_dummy IF EXISTS;
CREATE VIEW tmp_matts_dummy AS
SELECT id FROM civicrm_contact LIMIT 1;
```
and then drop it in the cleanup script...
