### ISSUE TITLE
Users can run SQL tasks

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.sqltasks#38]
It would be nice if users could run SQL Tasks, too.

I suggest to add another option to the task configuration, where you can define the permissions somebody has to have in order to execute the task. We could then create a page, where all accessible tasks that the current user is allowed to execute are listed, along with the description and a "run" button.

Obviously this is only about *running* a task, editing it will always be ``Administrator`` only.

**Comment by bjendres** [comment]
merged and ready for test in ``0.8-alpha1``

**Comment by magnolia61** [comment]
Using master and upgrading the extension it stalls. In the log I find: 
`[nativecode=1054 ** Unknown column 'run_permissions' in 'field list']"]`
Probably needs some upgrade code adjustments. FYI.

**Comment by bjendres** [comment]
@magnolia61 Thanks for the information, but it seems strange: The ``0.8-alpha1`` has the upgrade code right here: https://github.com/systopia/de.systopia.sqltasks/blob/0.8-alpha1/CRM/Sqltasks/Upgrader.php#L124-L144

Why would this code not have been executed on your system? Could you please check if
* the upgrade code was executed, but somehow failed to create the table, or
* wasn't executed in the first place, because in your system the extension version was already on ``0080``, maybe because of some prior dev version

That would really help.
