### ISSUE TITLE
menu location of sqltasks

### ISSUE THREAD

**Issue by magnolia61** [systopia/de.systopia.sqltasks#4]
Hi there,
Many extentions with general admin functionality are now placed in civicrm/admin
(under administer > administration console)

(for example: https://github.com/adixon/ca.civicrm.logviewer
and https://github.com/konadave/com.klangsoft.overrides)

Would it be possible to change the location to this place also?
thanks, with kind regards,
Richard van Oosterhout

**Comment by systopia** [comment]
Should be in ``master`` now. 

@magnolia61 Could you check? Don't forget to do ``menu/rebuild``...

**Comment by systopia** [comment]
Released with ``0.6.beta1``
