### ISSUE TITLE
Disabled tasks not clearly marked on shoreditch

### ISSUE THREAD

**Issue by systopia** [systopia/de.systopia.sqltasks#45]
If a task is disabled, it should be viewed in a 'grayed out' style in the sql taks manager. That does not work with the shoreditch theme.

Also, some of the buttons (e.g. in the "run now" screen) are not shoreditch compatible either.

**Comment by patf** [comment]
I think the buttons were fixed in fd89cceede9e35d2891b2f8027c5e2bd2c8a468f (unless we're talking about different screens), so that should be okay on >= `0.7.3.beta2`.
