### ISSUE TITLE
Error: Class 'CRM_Segmentation_Exporter' not found 

### ISSUE THREAD

**Issue by magnolia61** [systopia/de.systopia.sqltasks#5]
Just reporting, maybe this report is for your benefit,
When using the latest master code when I try to configure a task I get a fatal error and the following message in the log:
Error: Class 'CRM_Segmentation_Exporter' not found in CRM_Sqltasks_Action_SegmentationExport->buildForm() (line 70 of /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm_extensions/de.systopia.sqltasks/CRM/Sqltasks/Action/SegmentationExport.php).
Cheers, Richard

**Comment by systopia** [comment]
Thanks for the report. This should be fixed with the latest ``0.5.beta2``.

@magnolia61 Could you confirm this?

**Comment by magnolia61** [comment]
works like a charm now Björn.
This extension and civirules are my favorite should-be-core extensions ;-)

**Comment by systopia** [comment]
Glad to hear :)
