### ISSUE TITLE
support json-formatted api-parameter

### ISSUE THREAD

**Issue by thomst** [systopia/de.systopia.sqltasks#50]
Currently api-parameter have to be simple key-value-pairs.
It would be nice if json-encoded data-structures like lists and arrays would be supported.

**Comment by bjendres** [comment]
I have now implemented a json parameter parser, but only if the string starts with ``[``, ``{`` or ``"``. The latter I put, so you can still pass literal strings like ``[1,2,3]`` simply by enclosing them in double quotes.

@thomst: Could you verify that it works?

**Comment by bjendres** [comment]
oops, didn't mean to close this.

**Comment by bjendres** [comment]
@pfigel Could you (as a heavy user) see any side effects in this?

**Comment by pfigel** [comment]
@bjendres we don't recall having any tasks where we're passing API parameters that happen to be valid JSON arrays or objects. We can't rule out that we might have ones where double quote-enclosed strings are present in a token, but as that would only result in the quotes being stripped, we're okay with that risk.

(Great feature, by the way - we had a use-case for this a while back. 👍)

**Comment by bjendres** [comment]
merged and ready for test in ``0.8-alpha1``
