### ISSUE TITLE
Add file log setting

### ISSUE THREAD

**Issue by pfigel** [systopia/de.systopia.sqltasks#60]
When we have a lot of SQL tasks running at a specific time, we sometimes run out of space in the `civicrm_job_log.data` column (which stores the results of the API call executed by the scheduled job), causing SQL errors.

To avoid this, we should add an API parameter to enable logging of task results to a file rather than always returning it via API. The default should remain as-is.

**Comment by pfigel** [comment]
We have an existing implementation of https://github.com/greenpeace-cee/de.systopia.sqltasks/pull/2, but it conflicts with some upstream changes. @bjendres let's discuss it during the next merge session.

**Comment by bjendres** [comment]
Sounds like a very reasonable request.
