### ISSUE TITLE
Error on Upgrade to 0.8-alpha3

### ISSUE THREAD

**Issue by sluc23** [systopia/de.systopia.sqltasks#63]
Upgrading from `0.7.4` to `0.8-alpha3` got this error:
```
[db_error: message="DB Error: no such field" code=-19 mode=callback callback=CRM_Core_Error::exceptionHandler prefix="" info="UPDATE `civicrm_sqltasks` SET `name` = 'Export All Contacts', `description` = 'Export all Contacts', `category` = 'Export Task', `scheduled` = 'monthly', `enabled` = 0, `weight` = NULL, `parallel_exec` = NULL, `run_permissions` = NULL, `main_sql` = 'DROP TABLE IF EXISTS . . . ;', `post_sql` = 'DROP TABLE IF EXISTS . . . ;', `config` = '{ . . . }' WHERE id = 1 [nativecode=1054 ** Unknown column 'run_permissions' in 'field list']"]
```

investigating the cause now..

**Comment by sluc23** [comment]
I think the error is that upgrade hook `upgrade_0075` is saving config (with new column `run_permissions`), before upgrade hook `upgrade_0080` adds it..

https://github.com/systopia/de.systopia.sqltasks/blob/master/CRM/Sqltasks/Upgrader.php#L78

**Comment by pfigel** [comment]
I guess we could get away with renaming `upgrade_0075` to something like `upgrade_0081` so it runs afterwards? Might be easier than a workaround with a check in the config save code.

**Comment by bjendres** [comment]
There was a bit of a mix-up, also between the versions in the different branches. I have now tried to fix this with https://github.com/systopia/de.systopia.sqltasks/commit/e58a54e1e03fae74fdff16b0514afda0987e2c8e. Does this work for everybody?
