### ISSUE TITLE
Downloadable CSV file error

### ISSUE THREAD

**Issue by sluc23** [systopia/de.systopia.sqltasks#64]
When trying to download csv file generated by task an error is shown
url: `/civicrm/file?reset=1&id=4942&filename=allcontact_20-08-2019.csv.zip`

![Screenshot_2019-08-20 Screenshot](https://user-images.githubusercontent.com/2589799/63344152-062e2c00-c350-11e9-9cb6-5e70e2ea7205.png)

@pfigel I think we went through this in the AMS sprint and you fixed it.. didn't you?

**Comment by pfigel** [comment]
I remember discussing it, as it was something that broke while we were doing the security release, as a side-effect of [this](https://github.com/civicrm/civicrm-core/commit/6cb3fe2e3cc8b91c88d69ab3443ffc4270804aad).

I don't think we actually got around to fixing it. Basically, the existing infrastructure in `CRM_Core_Page_File` now seems to be intended only for two use-cases:

- Given a file ID, render a "proper" Civi file, i.e. stuff that's stored in `civicrm_file` e.g. via the Attachment API.
- Given a file path, render a small number of (mostly image) MIME types as defined in the `requestableMimeTypes` core setting.

The way it's used currently doesn't fit either of these use-cases.

What we could do:
- Handle file downloads independently within the extension. This is easy to get wrong and we could introduce vulnerabilities.
- Start using "proper" files. This would be nice in theory, but would require more thought and work.
- Add some (safe) MIME types to `requestableMimeTypes` as part of this extension and set the `mime-type` GET parameter in the download link. Relevant file types are probably `application/zip` and `text/csv`, but we don't really enforce this within the extension, so others would still be broken.
- Improve `CRM_Core_Page_File` to properly support this use case. For example, I think we could get away with arbitrary MIME types in the `Content-Disposition: download` case (that's the default unless you pass `download=0` in the URL). There seems to be no relevant security risk with that.

Might be worth opening a ticket in core to see what others think.

**Comment by bjendres** [comment]
Did I introduce this with my refactoring (#54)? It worked for me...

**Comment by pfigel** [comment]
Ah, I didn't actually see that there's already some `File.create` stuff in there that creates "proper" files, so some of what I said doesn't really make sense. 😬

I think the issue now is that the file row is not associated with an entity. Generally, stuff in `civicrm_file` is always linked to an entity via `civicrm_entity_file`. The download link is then built using the parameters `eid` (`civicrm_entity_file.entity_id`), `fid` (`civicrm_file.id`) and an access token `fcs`. This is done so download links "inherit" permissions from their associated entity (in other words, if I can access a contact, I can access their files). This is handled in `Civi\API\Subscriber\DynamicFKAuthorization`. However, this seems to be intended only for core tables.

The alternative way to build download links is with the file name, but then you're limited to the MIME types in `requestableMimeTypes`.

I think that still leaves us with these two options:
> - Add some (safe) MIME types to `requestableMimeTypes` as part of this extension and set the mime-type GET parameter in the download link. Relevant file types are probably `application/zip` and `text/csv`, but we don't really enforce this within the extension, so others would still be broken.
> - Improve `CRM_Core_Page_File` to properly support this use case. For example, I think we could get away with arbitrary MIME types in the `Content-Disposition: download` case (that's the default unless you pass `download=0` in the URL). There seems to be no relevant security risk with that.

@bjendres this code saw some core changes in 5.13.4 and in 5.14, perhaps you were testing with an earlier version?

**Comment by bjendres** [comment]
> @bjendres this code saw some core changes in 5.13.4 and in 5.14, perhaps you were testing with an earlier version?

That's entirely possible. 

> I think that still leaves us with these two options

I think we would have to implement the first option for sure, since there evidently are CiviCRM versions out there that have an issue right now. The second one seems like it could spark a big discussion, so it might take a while to come through.

@pfigel what do you think?

**Comment by bjendres** [comment]
Confirmed on ``5.16.1``. I'll have a look.

**Comment by bjendres** [comment]
This seems to be working for me now.

@sluc23 / @pfigel : Could you test again with ``master``?

**Comment by pfigel** [comment]
@bjendres I think we also need `application/zip` for ZIP files. CSV works for me now.

**Comment by bjendres** [comment]
Fair point. I added ``application/zip`` as well.

**Comment by bjendres** [comment]
@sluc23 does it work for you now? Then I'll create another alpha version

**Comment by sluc23** [comment]
I'll test it now, BTW related PR #66

**Comment by sluc23** [comment]
works!

**Comment by bjendres** [comment]
Pulled #66, seems to work as well. Also added ``l10n``

@sluc23 @pfigel should I release another ``alpha`` or is there anything missing?

**Comment by sluc23** [comment]
fixed! closing
