### ISSUE TITLE
Refactor im-/exporter file format

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.sqltasks#73]
The file format used for exporting (and importing) has a couple of drawbacks:

1. the ``last_runtime`` is exported, which causes a detected configuration difference if you store these configuration in a repository. It should not be included.
2. the JSON file format used has the disadvantage that the SQL scripts are unreadable in a diff.

We would like to change the file format as follows:
* the new file format should be distinguishable from the new one, and the importer should support both.
* should ideally be based on a given parser, e.g. YAML (see e.g. [here](https://yaml-multiline.info) or [here](https://til.hashrocket.com/posts/d7c96e2ee7-multiline-strings-in-yaml)).
* should that not be possible, create a simple-to-parse propriatory file system

**Comment by pfigel** [comment]
We're working on the config format in #75, so it would probably be best to do this as a follow-up.

**Comment by bjendres** [comment]
will be released in ``1.0``
