### ISSUE TITLE
mysql password in drupal dblog

### ISSUE THREAD

**Issue by magnolia61** [systopia/de.systopia.sqltasks#80]
Hi there,
I had am error in running an sql task and noticed the mysql ended up in the drupal dblog. I would assume this is not desirable. path and password below are dummies. Is this expected behaviour or not?

/var/www/vhosts/xyz/webroot/sites/all/modules/civicrm/CRM/Utils/File.php(350): DB_common->query("UPDATE `civicrm_value_table_140` SET `datum_vog_603` = NULL W...") #10 /var/www/vhosts/xyz/webroot/sites/all/modules/civicrm_extensions/de.systopia.sqltasks/CRM/Sqltasks/Task.php(328): CRM_Utils_File::runSqlQuery("mysql://adminxyz:G344HG%&@localhost/xyzdb_civi?new_link=true"

**Comment by bjendres** [comment]
Thanks for reporting @magnolia61. 

As far as I understand, the logging happens within ``CRM_Utils_File::runSqlQuery``, so that's not part of this extension. Also, shouldn't the logging only be done, when ``CIVICRM_DEBUG_LOG_QUERY`` is true?

But maybe I don't quite understand what you're referring to...

**Comment by magnolia61** [comment]
the query was a sqltask to empty some fields, but the field did not exist anymore.
I do not have CIVICRM_DEBUG_LOG_QUERY enabled. When the task ran, the log got created, with the DB password in it.

If I correct understand you, you think this is a core CiviCRM issue?

**Comment by bjendres** [comment]
I think we might have logged queries in the past, but I'm pretty sure we don't do it in the latest release. What version are you on?

**Comment by magnolia61** [comment]
running SQLtasks 2.0-dev and CiviCRM 5.29 beta1

**Comment by pfigel** [comment]
This looks like a backtrace being logged after an error/exception, which typically includes all the parameters being passed to a function - in this case including MySQL passwords.

I don't think there's really a way for us to change that behaviour within this extension - basically any exception thrown in Civi where this function is somewhere in the backtrace would cause these credentials to be logged. I don't think Civi currently makes any attempts to strip sensitive details out of logs/backtraces.

**Comment by bjendres** [comment]
> I don't think Civi currently makes any attempts to strip sensitive details out of logs/backtraces.

I'm not even sure that's possible in a generic way.

**Comment by bjendres** [comment]
But that seems to answer the question, thanks @pfigel. 

@magnolia61 can I close this?

**Comment by magnolia61** [comment]
@bjendres yep, Sorry for raising, I tought it was worthwile to report but it is clearly not a sqltask extension thing. Thanks for responding guys,

**Comment by bjendres** [comment]
Thanks for reporting, it's good to know this can happen :+1:
