### ISSUE TITLE
"activate" and "deactivate" are swapped in the menu.

### ISSUE THREAD

**Issue by bbaermann** [systopia/de.systopia.sqltasks#97]
In the ...-Menu at the right side of the manager-table the values for "activate" and "deactivate" are swapped. The functionality is right, but the wording is wrong. It says "activate" if the Task is already active and vice versa.

**Comment by pfigel** [comment]
@bbaermann does this still happen with the latest alpha version (and/or master)? Are you using Civi in a language other than English by any chance?

**Comment by bjendres** [comment]
I've had a quick look and it seemed a l10n issue. When I switched it to English, everything was fine. In German, it's reversed. Haven't spent much time to confirm this, though.

**Comment by bjendres** [comment]
fixed by #103
